name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
        poetry-version: ["latest"]
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python

        uses: actions/setup-python@v2
        with:
          python-version: 3.13.0

      - name: Install poetry
        run: |
          python -m pip install poetry==1.8.5

      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.in-project true

      - name: Cache the virtualenv
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: |
          python -m poetry install

      - name: Run tests
        run: |
          python -m poetry run python -m pytest -v
